set nobackup
set noswapfile
set number
set nowrap
set linebreak
set smartindent
set clipboard=unnamed
set softtabstop=2 shiftwidth=2 expandtab
set wildmenu
set incsearch
set hlsearch

syntax on
color elflord
execute pathogen#infect()

" Highlight all unwanted whitespace in red  
highlight ExtraWhitespace ctermbg=red guibg=red
autocmd BufWinEnter * let w:m1=matchadd('ExtraWhitespace', '\s\+$', -1)

" Highlight all emdashes [–] in red
highlight Emdash ctermbg=red guibg=red
autocmd BufWinEnter * let w:m2=matchadd('Emdash', '–\+', -1)

" Highlight all tabs [	] in blue
highlight TabChar ctermbg=black guibg=black
autocmd BufWinEnter * let w:m3=matchadd('TabChar', '\t\+', -1)

" Highlight all TODO in yellow
highlight ToDo ctermbg=yellow guibg=yellow
autocmd BufWinEnter * let w:m4=matchadd('ToDo', 'TODO', -1)

" Undo {{{
if exists("+undofile")
  "undofile - This allows you to use undos after exiting and restarting
  "This, like swap and backups, uses .vim-undo first, then ~/.vim-undo
  ":help undo-persistence
  "This is only present in 7.3+
  if isdirectory($HOME . '/.vim-undo') == 0
    :silent !mkdir -p ~/.vim-undo > /dev/null 2>&1
  endif
  set undodir=./.vim-undo//
  set undodir+=~/.vim-undo//
  set undofile
endif
" }}}
